require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
permissions_path = '../node_modules/react-native-permissions/ios'
platform :ios, '10.0'
target 'ApartnerApp' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  pod 'Firebase'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-blur', :path => '../node_modules/@react-native-community/blur'
  # pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
  # pod 'RNPDF', :path => '../node_modules/react-native-view-pdf'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  # target 'ApartnerAppTests' do
  #   inherit! :complete
  #   # Pods for testing
  # end
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!({'Flipper'=>'0.74.0'})
  post_install do |installer|
    react_native_post_install(installer)
    
  end
end